// <auto-generated />
using System;
using System.Text.Json;
using MarsVista.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarsVista.Api.Migrations
{
    [DbContext(typeof(MarsVistaDbContext))]
    [Migration("20251117053858_OptimizeManifestQueryCoveringIndex")]
    partial class OptimizeManifestQueryCoveringIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarsVista.Api.Entities.Camera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("RoverId")
                        .HasColumnType("integer")
                        .HasColumnName("rover_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_cameras");

                    b.HasIndex("RoverId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_cameras_rover_id_name");

                    b.ToTable("cameras", (string)null);
                });

            modelBuilder.Entity("MarsVista.Api.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attitude")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("attitude");

                    b.Property<int>("CameraId")
                        .HasColumnType("integer")
                        .HasColumnName("camera_id");

                    b.Property<string>("CameraModelType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("camera_model_type");

                    b.Property<string>("CameraPosition")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("camera_position");

                    b.Property<string>("CameraVector")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("camera_vector");

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Credit")
                        .HasColumnType("text")
                        .HasColumnName("credit");

                    b.Property<DateTime?>("DateReceived")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_received");

                    b.Property<string>("DateTakenMars")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("date_taken_mars");

                    b.Property<DateTime>("DateTakenUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_taken_utc");

                    b.Property<int?>("Drive")
                        .HasColumnType("integer")
                        .HasColumnName("drive");

                    b.Property<DateTime?>("EarthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("earth_date");

                    b.Property<string>("FilterName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("filter_name");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("ImgSrcFull")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("img_src_full");

                    b.Property<string>("ImgSrcLarge")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("img_src_large");

                    b.Property<string>("ImgSrcMedium")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("img_src_medium");

                    b.Property<string>("ImgSrcSmall")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("img_src_small");

                    b.Property<float?>("MastAz")
                        .HasColumnType("real")
                        .HasColumnName("mast_az");

                    b.Property<float?>("MastEl")
                        .HasColumnType("real")
                        .HasColumnName("mast_el");

                    b.Property<string>("NasaId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nasa_id");

                    b.Property<JsonDocument>("RawData")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data");

                    b.Property<int>("RoverId")
                        .HasColumnType("integer")
                        .HasColumnName("rover_id");

                    b.Property<string>("SampleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sample_type");

                    b.Property<int?>("Site")
                        .HasColumnType("integer")
                        .HasColumnName("site");

                    b.Property<int>("Sol")
                        .HasColumnType("integer")
                        .HasColumnName("sol");

                    b.Property<float?>("SpacecraftClock")
                        .HasColumnType("real")
                        .HasColumnName("spacecraft_clock");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.Property<string>("Xyz")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("xyz");

                    b.HasKey("Id")
                        .HasName("pk_photos");

                    b.HasIndex("CameraId")
                        .HasDatabaseName("ix_photos_camera_id");

                    b.HasIndex("DateTakenUtc")
                        .HasDatabaseName("ix_photos_date_taken_utc");

                    b.HasIndex("EarthDate")
                        .HasDatabaseName("ix_photos_earth_date");

                    b.HasIndex("NasaId")
                        .IsUnique()
                        .HasDatabaseName("ix_photos_nasa_id");

                    b.HasIndex("Sol")
                        .HasDatabaseName("ix_photos_sol");

                    b.HasIndex("MastAz", "MastEl")
                        .HasDatabaseName("ix_photos_mast_az_mast_el");

                    b.HasIndex("RoverId", "Sol")
                        .HasDatabaseName("ix_photos_rover_id_sol");

                    b.HasIndex("Site", "Drive")
                        .HasDatabaseName("ix_photos_site_drive");

                    b.HasIndex("RoverId", "CameraId", "Sol")
                        .HasDatabaseName("ix_photos_rover_id_camera_id_sol");

                    b.ToTable("photos", (string)null);
                });

            modelBuilder.Entity("MarsVista.Api.Entities.Rover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("LandingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("landing_date");

                    b.Property<DateTime?>("LaunchDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("launch_date");

                    b.Property<DateTime?>("MaxDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("max_date");

                    b.Property<int?>("MaxSol")
                        .HasColumnType("integer")
                        .HasColumnName("max_sol");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int?>("TotalPhotos")
                        .HasColumnType("integer")
                        .HasColumnName("total_photos");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_rovers");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_rovers_name");

                    b.ToTable("rovers", (string)null);
                });

            modelBuilder.Entity("MarsVista.Api.Entities.Camera", b =>
                {
                    b.HasOne("MarsVista.Api.Entities.Rover", "Rover")
                        .WithMany("Cameras")
                        .HasForeignKey("RoverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cameras_rovers_rover_id");

                    b.Navigation("Rover");
                });

            modelBuilder.Entity("MarsVista.Api.Entities.Photo", b =>
                {
                    b.HasOne("MarsVista.Api.Entities.Camera", "Camera")
                        .WithMany("Photos")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_photos_cameras_camera_id");

                    b.HasOne("MarsVista.Api.Entities.Rover", "Rover")
                        .WithMany("Photos")
                        .HasForeignKey("RoverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_photos_rovers_rover_id");

                    b.Navigation("Camera");

                    b.Navigation("Rover");
                });

            modelBuilder.Entity("MarsVista.Api.Entities.Camera", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("MarsVista.Api.Entities.Rover", b =>
                {
                    b.Navigation("Cameras");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
