/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all unique locations visited by rovers */
        get: {
            parameters: {
                query?: {
                    /** @description Comma-separated list of rover names */
                    rovers?: string;
                    /** @description Minimum sol */
                    sol_min?: number;
                    /** @description Maximum sol */
                    sol_max?: number;
                    /** @description Minimum number of photos at location */
                    min_photos?: number;
                    /** @description Page number (1-indexed) */
                    page?: number;
                    /** @description Items per page (default: 25, max: 100) */
                    per_page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LocationResourceListApiResponse"];
                        "application/json": components["schemas"]["LocationResourceListApiResponse"];
                        "text/json": components["schemas"]["LocationResourceListApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiError"];
                        "application/json": components["schemas"]["ApiError"];
                        "text/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/locations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific location by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Location ID (e.g., curiosity_79_1204) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LocationResource"];
                        "application/json": components["schemas"]["LocationResource"];
                        "text/json": components["schemas"]["LocationResource"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiError"];
                        "application/json": components["schemas"]["ApiError"];
                        "text/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/panoramas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all detected panoramas */
        get: {
            parameters: {
                query?: {
                    /** @description Comma-separated list of rover names (curiosity, perseverance, etc.) */
                    rovers?: string;
                    /** @description Minimum sol */
                    sol_min?: number;
                    /** @description Maximum sol */
                    sol_max?: number;
                    /** @description Minimum number of photos in panorama */
                    min_photos?: number;
                    /** @description Page number (1-indexed) */
                    page?: number;
                    /** @description Items per page (default: 25, max: 100) */
                    per_page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PanoramaResourceListApiResponse"];
                        "application/json": components["schemas"]["PanoramaResourceListApiResponse"];
                        "text/json": components["schemas"]["PanoramaResourceListApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiError"];
                        "application/json": components["schemas"]["ApiError"];
                        "text/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/panoramas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific panorama by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Panorama ID (e.g., pano_curiosity_1000_14) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PanoramaResource"];
                        "application/json": components["schemas"]["PanoramaResource"];
                        "text/json": components["schemas"]["PanoramaResource"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiError"];
                        "application/json": components["schemas"]["ApiError"];
                        "text/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/time-machine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get photos from the same location at different times */
        get: {
            parameters: {
                query?: {
                    /** @description Site number (required) */
                    site?: number;
                    /** @description Drive number (required) */
                    drive?: number;
                    /** @description Rover name filter */
                    rover?: string;
                    /** @description Mars local time filter (e.g., M14:00:00) */
                    mars_time?: string;
                    /** @description Camera name filter */
                    camera?: string;
                    /** @description Maximum number of results (default: 100) */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TimeMachineResponse"];
                        "application/json": components["schemas"]["TimeMachineResponse"];
                        "text/json": components["schemas"]["TimeMachineResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiError"];
                        "application/json": components["schemas"]["ApiError"];
                        "text/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all cameras across all rovers */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CameraResourceListApiResponse"];
                        "application/json": components["schemas"]["CameraResourceListApiResponse"];
                        "text/json": components["schemas"]["CameraResourceListApiResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/cameras/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific camera by ID (name) */
        get: {
            parameters: {
                query?: {
                    /** @description Optional rover filter */
                    rover?: string;
                };
                header?: never;
                path: {
                    /** @description Camera name (e.g., FHAZ, MAST) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CameraResourceApiResponse"];
                        "application/json": components["schemas"]["CameraResourceApiResponse"];
                        "text/json": components["schemas"]["CameraResourceApiResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiError"];
                        "application/json": components["schemas"]["ApiError"];
                        "text/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Search by NASA ID (partial match, case-insensitive)
                     *     Example: nasa_id=NLB_780234
                     */
                    nasa_id?: string;
                    /**
                     * @description Filter by one or more rovers (comma-separated)
                     *     Example: rovers=curiosity,perseverance
                     */
                    rovers?: string;
                    /**
                     * @description Filter by one or more cameras (comma-separated)
                     *     Example: cameras=FHAZ,NAVCAM,MAST
                     */
                    cameras?: string;
                    /** @description Minimum sol (inclusive) */
                    sol_min?: number;
                    /** @description Maximum sol (inclusive) */
                    sol_max?: number;
                    sol?: number;
                    /** @description Minimum earth date (inclusive, YYYY-MM-DD format) */
                    date_min?: string;
                    /** @description Maximum earth date (inclusive, YYYY-MM-DD format) */
                    date_max?: string;
                    /** @description Exact earth date (shorthand, YYYY-MM-DD format) */
                    earth_date?: string;
                    /**
                     * @description Sort fields (comma-separated, prefix with - for descending)
                     *     Example: sort=-earth_date,camera
                     */
                    sort?: string;
                    /**
                     * @description Fields to include (comma-separated, for sparse fieldsets)
                     *     Example: fields=id,img_src,sol,earth_date
                     */
                    fields?: string;
                    /**
                     * @description Related resources to include (comma-separated)
                     *     Example: include=rover,camera
                     */
                    include?: string;
                    /** @description Page number (1-indexed, default: 1) */
                    page?: number;
                    /** @description Items per page (default: 25, max: 100) */
                    per_page?: number;
                    /** @description Cursor for cursor-based pagination (base64-encoded) */
                    cursor?: string;
                    /**
                     * @description Minimum Mars local time (format: Mhh:mm:ss or hh:mm:ss)
                     *     Example: M06:00:00 for 6 AM Mars time
                     */
                    mars_time_min?: string;
                    /**
                     * @description Maximum Mars local time (format: Mhh:mm:ss or hh:mm:ss)
                     *     Example: M18:00:00 for 6 PM Mars time
                     */
                    mars_time_max?: string;
                    /** @description Filter for golden hour photos (sunrise/sunset lighting) */
                    mars_time_golden_hour?: boolean;
                    /** @description Exact site number */
                    site?: number;
                    /** @description Minimum site number (inclusive) */
                    site_min?: number;
                    /** @description Maximum site number (inclusive) */
                    site_max?: number;
                    /** @description Exact drive number */
                    drive?: number;
                    /** @description Minimum drive number (inclusive) */
                    drive_min?: number;
                    /** @description Maximum drive number (inclusive) */
                    drive_max?: number;
                    location_radius?: number;
                    /** @description Minimum image width in pixels */
                    min_width?: number;
                    /** @description Minimum image height in pixels */
                    min_height?: number;
                    /** @description Maximum image width in pixels */
                    max_width?: number;
                    /** @description Maximum image height in pixels */
                    max_height?: number;
                    /**
                     * @description Filter by sample type (e.g., "Full", "Thumbnail", "Subframe")
                     *     Comma-separated for multiple types
                     */
                    sample_type?: string;
                    /** @description Filter by aspect ratio (e.g., "16:9", "4:3", "1:1") */
                    aspect_ratio?: string;
                    /**
                     * @description Minimum mast elevation angle in degrees
                     *     Negative = looking down, Positive = looking up
                     */
                    mast_elevation_min?: number;
                    /** @description Maximum mast elevation angle in degrees */
                    mast_elevation_max?: number;
                    /** @description Minimum mast azimuth angle in degrees (0-360) */
                    mast_azimuth_min?: number;
                    /** @description Maximum mast azimuth angle in degrees (0-360) */
                    mast_azimuth_max?: number;
                    /**
                     * @description Field set preset (minimal, standard, extended, scientific, complete)
                     *     Can also be comma-separated field names for custom selection
                     */
                    field_set?: string;
                    /**
                     * @description Specific image sizes to include (comma-separated: small, medium, large, full)
                     *     Default: all sizes
                     */
                    image_sizes?: string;
                    /** @description Exclude images entirely (metadata only) */
                    exclude_images?: boolean;
                    /** @description Parsed rover names (lowercase) */
                    RoverList?: string[];
                    /** @description Parsed camera names (uppercase) */
                    CameraList?: string[];
                    /** @description Parsed sort fields with direction */
                    SortFields?: components["schemas"]["SortField"][];
                    /** @description Parsed field names for sparse fieldsets */
                    FieldList?: string[];
                    /** @description Parsed include resource names */
                    IncludeList?: string[];
                    /** @description Parsed minimum date */
                    DateMinParsed?: string;
                    /** @description Parsed maximum date */
                    DateMaxParsed?: string;
                    /** @description Effective page number (with default) */
                    PageNumber?: number;
                    /** @description Effective page size (with default, capped at 100) */
                    PageSize?: number;
                    /** @description Parsed Mars time minimum (TimeSpan from midnight) */
                    MarsTimeMinParsed?: string;
                    /** @description Parsed Mars time maximum (TimeSpan from midnight) */
                    MarsTimeMaxParsed?: string;
                    /** @description Parsed sample types list */
                    SampleTypeList?: string[];
                    /** @description Parsed aspect ratio (width:height) */
                    AspectRatioParsed?: components["schemas"]["Int32Int32ValueTuple"];
                    /** @description Parsed field set enum value */
                    FieldSetParsed?: components["schemas"]["FieldSetType"];
                    /** @description Parsed image sizes list */
                    ImageSizesList?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PhotoResourceListApiResponse"];
                        "application/json": components["schemas"]["PhotoResourceListApiResponse"];
                        "text/json": components["schemas"]["PhotoResourceListApiResponse"];
                    };
                };
                /** @description Not Modified */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiError"];
                        "application/json": components["schemas"]["ApiError"];
                        "text/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/photos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific photo by ID */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Search by NASA ID (partial match, case-insensitive)
                     *     Example: nasa_id=NLB_780234
                     */
                    nasa_id?: string;
                    /**
                     * @description Filter by one or more rovers (comma-separated)
                     *     Example: rovers=curiosity,perseverance
                     */
                    rovers?: string;
                    /**
                     * @description Filter by one or more cameras (comma-separated)
                     *     Example: cameras=FHAZ,NAVCAM,MAST
                     */
                    cameras?: string;
                    /** @description Minimum sol (inclusive) */
                    sol_min?: number;
                    /** @description Maximum sol (inclusive) */
                    sol_max?: number;
                    sol?: number;
                    /** @description Minimum earth date (inclusive, YYYY-MM-DD format) */
                    date_min?: string;
                    /** @description Maximum earth date (inclusive, YYYY-MM-DD format) */
                    date_max?: string;
                    /** @description Exact earth date (shorthand, YYYY-MM-DD format) */
                    earth_date?: string;
                    /**
                     * @description Sort fields (comma-separated, prefix with - for descending)
                     *     Example: sort=-earth_date,camera
                     */
                    sort?: string;
                    /**
                     * @description Fields to include (comma-separated, for sparse fieldsets)
                     *     Example: fields=id,img_src,sol,earth_date
                     */
                    fields?: string;
                    /**
                     * @description Related resources to include (comma-separated)
                     *     Example: include=rover,camera
                     */
                    include?: string;
                    /** @description Page number (1-indexed, default: 1) */
                    page?: number;
                    /** @description Items per page (default: 25, max: 100) */
                    per_page?: number;
                    /** @description Cursor for cursor-based pagination (base64-encoded) */
                    cursor?: string;
                    /**
                     * @description Minimum Mars local time (format: Mhh:mm:ss or hh:mm:ss)
                     *     Example: M06:00:00 for 6 AM Mars time
                     */
                    mars_time_min?: string;
                    /**
                     * @description Maximum Mars local time (format: Mhh:mm:ss or hh:mm:ss)
                     *     Example: M18:00:00 for 6 PM Mars time
                     */
                    mars_time_max?: string;
                    /** @description Filter for golden hour photos (sunrise/sunset lighting) */
                    mars_time_golden_hour?: boolean;
                    /** @description Exact site number */
                    site?: number;
                    /** @description Minimum site number (inclusive) */
                    site_min?: number;
                    /** @description Maximum site number (inclusive) */
                    site_max?: number;
                    /** @description Exact drive number */
                    drive?: number;
                    /** @description Minimum drive number (inclusive) */
                    drive_min?: number;
                    /** @description Maximum drive number (inclusive) */
                    drive_max?: number;
                    location_radius?: number;
                    /** @description Minimum image width in pixels */
                    min_width?: number;
                    /** @description Minimum image height in pixels */
                    min_height?: number;
                    /** @description Maximum image width in pixels */
                    max_width?: number;
                    /** @description Maximum image height in pixels */
                    max_height?: number;
                    /**
                     * @description Filter by sample type (e.g., "Full", "Thumbnail", "Subframe")
                     *     Comma-separated for multiple types
                     */
                    sample_type?: string;
                    /** @description Filter by aspect ratio (e.g., "16:9", "4:3", "1:1") */
                    aspect_ratio?: string;
                    /**
                     * @description Minimum mast elevation angle in degrees
                     *     Negative = looking down, Positive = looking up
                     */
                    mast_elevation_min?: number;
                    /** @description Maximum mast elevation angle in degrees */
                    mast_elevation_max?: number;
                    /** @description Minimum mast azimuth angle in degrees (0-360) */
                    mast_azimuth_min?: number;
                    /** @description Maximum mast azimuth angle in degrees (0-360) */
                    mast_azimuth_max?: number;
                    /**
                     * @description Field set preset (minimal, standard, extended, scientific, complete)
                     *     Can also be comma-separated field names for custom selection
                     */
                    field_set?: string;
                    /**
                     * @description Specific image sizes to include (comma-separated: small, medium, large, full)
                     *     Default: all sizes
                     */
                    image_sizes?: string;
                    /** @description Exclude images entirely (metadata only) */
                    exclude_images?: boolean;
                    /** @description Parsed rover names (lowercase) */
                    RoverList?: string[];
                    /** @description Parsed camera names (uppercase) */
                    CameraList?: string[];
                    /** @description Parsed sort fields with direction */
                    SortFields?: components["schemas"]["SortField"][];
                    /** @description Parsed field names for sparse fieldsets */
                    FieldList?: string[];
                    /** @description Parsed include resource names */
                    IncludeList?: string[];
                    /** @description Parsed minimum date */
                    DateMinParsed?: string;
                    /** @description Parsed maximum date */
                    DateMaxParsed?: string;
                    /** @description Effective page number (with default) */
                    PageNumber?: number;
                    /** @description Effective page size (with default, capped at 100) */
                    PageSize?: number;
                    /** @description Parsed Mars time minimum (TimeSpan from midnight) */
                    MarsTimeMinParsed?: string;
                    /** @description Parsed Mars time maximum (TimeSpan from midnight) */
                    MarsTimeMaxParsed?: string;
                    /** @description Parsed sample types list */
                    SampleTypeList?: string[];
                    /** @description Parsed aspect ratio (width:height) */
                    AspectRatioParsed?: components["schemas"]["Int32Int32ValueTuple"];
                    /** @description Parsed field set enum value */
                    FieldSetParsed?: components["schemas"]["FieldSetType"];
                    /** @description Parsed image sizes list */
                    ImageSizesList?: string[];
                };
                header?: never;
                path: {
                    /** @description Photo ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PhotoResourceApiResponse"];
                        "application/json": components["schemas"]["PhotoResourceApiResponse"];
                        "text/json": components["schemas"]["PhotoResourceApiResponse"];
                    };
                };
                /** @description Not Modified */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiError"];
                        "application/json": components["schemas"]["ApiError"];
                        "text/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/photos/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Search by NASA ID (partial match, case-insensitive)
                     *     Example: nasa_id=NLB_780234
                     */
                    nasa_id?: string;
                    /**
                     * @description Filter by one or more rovers (comma-separated)
                     *     Example: rovers=curiosity,perseverance
                     */
                    rovers?: string;
                    /**
                     * @description Filter by one or more cameras (comma-separated)
                     *     Example: cameras=FHAZ,NAVCAM,MAST
                     */
                    cameras?: string;
                    /** @description Minimum sol (inclusive) */
                    sol_min?: number;
                    /** @description Maximum sol (inclusive) */
                    sol_max?: number;
                    sol?: number;
                    /** @description Minimum earth date (inclusive, YYYY-MM-DD format) */
                    date_min?: string;
                    /** @description Maximum earth date (inclusive, YYYY-MM-DD format) */
                    date_max?: string;
                    /** @description Exact earth date (shorthand, YYYY-MM-DD format) */
                    earth_date?: string;
                    /**
                     * @description Sort fields (comma-separated, prefix with - for descending)
                     *     Example: sort=-earth_date,camera
                     */
                    sort?: string;
                    /**
                     * @description Fields to include (comma-separated, for sparse fieldsets)
                     *     Example: fields=id,img_src,sol,earth_date
                     */
                    fields?: string;
                    /**
                     * @description Related resources to include (comma-separated)
                     *     Example: include=rover,camera
                     */
                    include?: string;
                    /** @description Page number (1-indexed, default: 1) */
                    page?: number;
                    /** @description Items per page (default: 25, max: 100) */
                    per_page?: number;
                    /** @description Cursor for cursor-based pagination (base64-encoded) */
                    cursor?: string;
                    /**
                     * @description Minimum Mars local time (format: Mhh:mm:ss or hh:mm:ss)
                     *     Example: M06:00:00 for 6 AM Mars time
                     */
                    mars_time_min?: string;
                    /**
                     * @description Maximum Mars local time (format: Mhh:mm:ss or hh:mm:ss)
                     *     Example: M18:00:00 for 6 PM Mars time
                     */
                    mars_time_max?: string;
                    /** @description Filter for golden hour photos (sunrise/sunset lighting) */
                    mars_time_golden_hour?: boolean;
                    /** @description Exact site number */
                    site?: number;
                    /** @description Minimum site number (inclusive) */
                    site_min?: number;
                    /** @description Maximum site number (inclusive) */
                    site_max?: number;
                    /** @description Exact drive number */
                    drive?: number;
                    /** @description Minimum drive number (inclusive) */
                    drive_min?: number;
                    /** @description Maximum drive number (inclusive) */
                    drive_max?: number;
                    location_radius?: number;
                    /** @description Minimum image width in pixels */
                    min_width?: number;
                    /** @description Minimum image height in pixels */
                    min_height?: number;
                    /** @description Maximum image width in pixels */
                    max_width?: number;
                    /** @description Maximum image height in pixels */
                    max_height?: number;
                    /**
                     * @description Filter by sample type (e.g., "Full", "Thumbnail", "Subframe")
                     *     Comma-separated for multiple types
                     */
                    sample_type?: string;
                    /** @description Filter by aspect ratio (e.g., "16:9", "4:3", "1:1") */
                    aspect_ratio?: string;
                    /**
                     * @description Minimum mast elevation angle in degrees
                     *     Negative = looking down, Positive = looking up
                     */
                    mast_elevation_min?: number;
                    /** @description Maximum mast elevation angle in degrees */
                    mast_elevation_max?: number;
                    /** @description Minimum mast azimuth angle in degrees (0-360) */
                    mast_azimuth_min?: number;
                    /** @description Maximum mast azimuth angle in degrees (0-360) */
                    mast_azimuth_max?: number;
                    /**
                     * @description Field set preset (minimal, standard, extended, scientific, complete)
                     *     Can also be comma-separated field names for custom selection
                     */
                    field_set?: string;
                    /**
                     * @description Specific image sizes to include (comma-separated: small, medium, large, full)
                     *     Default: all sizes
                     */
                    image_sizes?: string;
                    /** @description Exclude images entirely (metadata only) */
                    exclude_images?: boolean;
                    /** @description Parsed rover names (lowercase) */
                    RoverList?: string[];
                    /** @description Parsed camera names (uppercase) */
                    CameraList?: string[];
                    /** @description Parsed sort fields with direction */
                    SortFields?: components["schemas"]["SortField"][];
                    /** @description Parsed field names for sparse fieldsets */
                    FieldList?: string[];
                    /** @description Parsed include resource names */
                    IncludeList?: string[];
                    /** @description Parsed minimum date */
                    DateMinParsed?: string;
                    /** @description Parsed maximum date */
                    DateMaxParsed?: string;
                    /** @description Effective page number (with default) */
                    PageNumber?: number;
                    /** @description Effective page size (with default, capped at 100) */
                    PageSize?: number;
                    /** @description Parsed Mars time minimum (TimeSpan from midnight) */
                    MarsTimeMinParsed?: string;
                    /** @description Parsed Mars time maximum (TimeSpan from midnight) */
                    MarsTimeMaxParsed?: string;
                    /** @description Parsed sample types list */
                    SampleTypeList?: string[];
                    /** @description Parsed aspect ratio (width:height) */
                    AspectRatioParsed?: components["schemas"]["Int32Int32ValueTuple"];
                    /** @description Parsed field set enum value */
                    FieldSetParsed?: components["schemas"]["FieldSetType"];
                    /** @description Parsed image sizes list */
                    ImageSizesList?: string[];
                    group_by?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PhotoStatisticsResponseApiResponse"];
                        "application/json": components["schemas"]["PhotoStatisticsResponseApiResponse"];
                        "text/json": components["schemas"]["PhotoStatisticsResponseApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiError"];
                        "application/json": components["schemas"]["ApiError"];
                        "text/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/photos/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch retrieve photos by IDs
         * @description Efficiently retrieve multiple photos in a single request.
         *     Maximum 100 IDs per request.
         */
        post: {
            parameters: {
                query?: {
                    /**
                     * @description Search by NASA ID (partial match, case-insensitive)
                     *     Example: nasa_id=NLB_780234
                     */
                    nasa_id?: string;
                    /**
                     * @description Filter by one or more rovers (comma-separated)
                     *     Example: rovers=curiosity,perseverance
                     */
                    rovers?: string;
                    /**
                     * @description Filter by one or more cameras (comma-separated)
                     *     Example: cameras=FHAZ,NAVCAM,MAST
                     */
                    cameras?: string;
                    /** @description Minimum sol (inclusive) */
                    sol_min?: number;
                    /** @description Maximum sol (inclusive) */
                    sol_max?: number;
                    sol?: number;
                    /** @description Minimum earth date (inclusive, YYYY-MM-DD format) */
                    date_min?: string;
                    /** @description Maximum earth date (inclusive, YYYY-MM-DD format) */
                    date_max?: string;
                    /** @description Exact earth date (shorthand, YYYY-MM-DD format) */
                    earth_date?: string;
                    /**
                     * @description Sort fields (comma-separated, prefix with - for descending)
                     *     Example: sort=-earth_date,camera
                     */
                    sort?: string;
                    /**
                     * @description Fields to include (comma-separated, for sparse fieldsets)
                     *     Example: fields=id,img_src,sol,earth_date
                     */
                    fields?: string;
                    /**
                     * @description Related resources to include (comma-separated)
                     *     Example: include=rover,camera
                     */
                    include?: string;
                    /** @description Page number (1-indexed, default: 1) */
                    page?: number;
                    /** @description Items per page (default: 25, max: 100) */
                    per_page?: number;
                    /** @description Cursor for cursor-based pagination (base64-encoded) */
                    cursor?: string;
                    /**
                     * @description Minimum Mars local time (format: Mhh:mm:ss or hh:mm:ss)
                     *     Example: M06:00:00 for 6 AM Mars time
                     */
                    mars_time_min?: string;
                    /**
                     * @description Maximum Mars local time (format: Mhh:mm:ss or hh:mm:ss)
                     *     Example: M18:00:00 for 6 PM Mars time
                     */
                    mars_time_max?: string;
                    /** @description Filter for golden hour photos (sunrise/sunset lighting) */
                    mars_time_golden_hour?: boolean;
                    /** @description Exact site number */
                    site?: number;
                    /** @description Minimum site number (inclusive) */
                    site_min?: number;
                    /** @description Maximum site number (inclusive) */
                    site_max?: number;
                    /** @description Exact drive number */
                    drive?: number;
                    /** @description Minimum drive number (inclusive) */
                    drive_min?: number;
                    /** @description Maximum drive number (inclusive) */
                    drive_max?: number;
                    location_radius?: number;
                    /** @description Minimum image width in pixels */
                    min_width?: number;
                    /** @description Minimum image height in pixels */
                    min_height?: number;
                    /** @description Maximum image width in pixels */
                    max_width?: number;
                    /** @description Maximum image height in pixels */
                    max_height?: number;
                    /**
                     * @description Filter by sample type (e.g., "Full", "Thumbnail", "Subframe")
                     *     Comma-separated for multiple types
                     */
                    sample_type?: string;
                    /** @description Filter by aspect ratio (e.g., "16:9", "4:3", "1:1") */
                    aspect_ratio?: string;
                    /**
                     * @description Minimum mast elevation angle in degrees
                     *     Negative = looking down, Positive = looking up
                     */
                    mast_elevation_min?: number;
                    /** @description Maximum mast elevation angle in degrees */
                    mast_elevation_max?: number;
                    /** @description Minimum mast azimuth angle in degrees (0-360) */
                    mast_azimuth_min?: number;
                    /** @description Maximum mast azimuth angle in degrees (0-360) */
                    mast_azimuth_max?: number;
                    /**
                     * @description Field set preset (minimal, standard, extended, scientific, complete)
                     *     Can also be comma-separated field names for custom selection
                     */
                    field_set?: string;
                    /**
                     * @description Specific image sizes to include (comma-separated: small, medium, large, full)
                     *     Default: all sizes
                     */
                    image_sizes?: string;
                    /** @description Exclude images entirely (metadata only) */
                    exclude_images?: boolean;
                    /** @description Parsed rover names (lowercase) */
                    RoverList?: string[];
                    /** @description Parsed camera names (uppercase) */
                    CameraList?: string[];
                    /** @description Parsed sort fields with direction */
                    SortFields?: components["schemas"]["SortField"][];
                    /** @description Parsed field names for sparse fieldsets */
                    FieldList?: string[];
                    /** @description Parsed include resource names */
                    IncludeList?: string[];
                    /** @description Parsed minimum date */
                    DateMinParsed?: string;
                    /** @description Parsed maximum date */
                    DateMaxParsed?: string;
                    /** @description Effective page number (with default) */
                    PageNumber?: number;
                    /** @description Effective page size (with default, capped at 100) */
                    PageSize?: number;
                    /** @description Parsed Mars time minimum (TimeSpan from midnight) */
                    MarsTimeMinParsed?: string;
                    /** @description Parsed Mars time maximum (TimeSpan from midnight) */
                    MarsTimeMaxParsed?: string;
                    /** @description Parsed sample types list */
                    SampleTypeList?: string[];
                    /** @description Parsed aspect ratio (width:height) */
                    AspectRatioParsed?: components["schemas"]["Int32Int32ValueTuple"];
                    /** @description Parsed field set enum value */
                    FieldSetParsed?: components["schemas"]["FieldSetType"];
                    /** @description Parsed image sizes list */
                    ImageSizesList?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["BatchPhotoRequest"];
                    "text/json": components["schemas"]["BatchPhotoRequest"];
                    "application/*+json": components["schemas"]["BatchPhotoRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PhotoResourceListApiResponse"];
                        "application/json": components["schemas"]["PhotoResourceListApiResponse"];
                        "text/json": components["schemas"]["PhotoResourceListApiResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiError"];
                        "application/json": components["schemas"]["ApiError"];
                        "text/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/rovers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all rovers */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RoverResourceListApiResponse"];
                        "application/json": components["schemas"]["RoverResourceListApiResponse"];
                        "text/json": components["schemas"]["RoverResourceListApiResponse"];
                    };
                };
                /** @description Not Modified */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/rovers/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific rover by slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Rover slug (curiosity, perseverance, opportunity, spirit) */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RoverResourceApiResponse"];
                        "application/json": components["schemas"]["RoverResourceApiResponse"];
                        "text/json": components["schemas"]["RoverResourceApiResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiError"];
                        "application/json": components["schemas"]["ApiError"];
                        "text/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/rovers/{slug}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get rover manifest (photo history by sol) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Rover slug */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RoverManifestApiResponse"];
                        "application/json": components["schemas"]["RoverManifestApiResponse"];
                        "text/json": components["schemas"]["RoverManifestApiResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiError"];
                        "application/json": components["schemas"]["ApiError"];
                        "text/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/rovers/{slug}/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get cameras for a specific rover */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Rover slug */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CameraResourceListApiResponse"];
                        "application/json": components["schemas"]["CameraResourceListApiResponse"];
                        "text/json": components["schemas"]["CameraResourceListApiResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiError"];
                        "application/json": components["schemas"]["ApiError"];
                        "text/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/rovers/{slug}/journey": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get journey tracking data for a rover */
        get: {
            parameters: {
                query?: {
                    /** @description Minimum sol */
                    sol_min?: number;
                    /** @description Maximum sol */
                    sol_max?: number;
                };
                header?: never;
                path: {
                    /** @description Rover slug */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["JourneyResourceApiResponse"];
                        "application/json": components["schemas"]["JourneyResourceApiResponse"];
                        "text/json": components["schemas"]["JourneyResourceApiResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiError"];
                        "application/json": components["schemas"]["ApiError"];
                        "text/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description RFC 7807 Problem Details for HTTP APIs
         *     Provides machine-readable error responses with detailed field-level validation errors
         */
        ApiError: {
            /** @description A URI reference that identifies the problem type */
            type?: string | null;
            /** @description A short, human-readable summary of the problem type */
            title?: string | null;
            /**
             * Format: int32
             * @description The HTTP status code
             */
            status?: number;
            /** @description A human-readable explanation specific to this occurrence of the problem */
            detail?: string | null;
            /** @description A URI reference that identifies the specific occurrence of the problem */
            instance?: string | null;
            /** @description Field-level validation errors */
            errors?: components["schemas"]["ValidationError"][] | null;
            /**
             * Format: date-time
             * @description Response timestamp
             */
            timestamp?: string;
        };
        /** @description Request model for batch photo retrieval */
        BatchPhotoRequest: {
            /** @description List of photo IDs to retrieve (maximum 100) */
            ids?: number[] | null;
        };
        /** @description Camera attributes */
        CameraAttributes: {
            /** @description Full camera name */
            fullName?: string | null;
            /**
             * Format: int32
             * @description Number of photos from this camera (when included in statistics)
             */
            photoCount?: number | null;
        };
        /** @description Camera reference with attributes */
        CameraReference: {
            /** @description Camera identifier (name like "FHAZ", "MAST") */
            id?: string | null;
            /** @description Resource type (always "camera") */
            type?: string | null;
            attributes?: components["schemas"]["CameraAttributes"];
        };
        /** @description Camera relationships */
        CameraRelationships: {
            rover?: components["schemas"]["ResourceReference"];
        };
        /** @description Camera resource in v2 API format */
        CameraResource: {
            /** @description Camera identifier (name like "FHAZ", "MAST") */
            id?: string | null;
            /** @description Resource type (always "camera") */
            type?: string | null;
            attributes?: components["schemas"]["CameraResourceAttributes"];
            relationships?: components["schemas"]["CameraRelationships"];
        };
        /**
         * @description Standardized API response envelope for v2 endpoints
         *     Inspired by JSON:API specification for consistency
         */
        CameraResourceApiResponse: {
            data?: components["schemas"]["CameraResource"];
            meta?: components["schemas"]["ResponseMeta"];
            pagination?: components["schemas"]["PaginationInfo"];
            links?: components["schemas"]["ResponseLinks"];
        };
        /** @description Camera attributes */
        CameraResourceAttributes: {
            /** @description Camera name (e.g., "FHAZ", "MAST") */
            name?: string | null;
            /** @description Full camera name (e.g., "Front Hazard Avoidance Camera") */
            fullName?: string | null;
            /**
             * Format: int32
             * @description Total number of photos from this camera
             */
            photoCount?: number | null;
            /**
             * Format: int32
             * @description First sol with photos from this camera
             */
            firstPhotoSol?: number | null;
            /**
             * Format: int32
             * @description Last sol with photos from this camera
             */
            lastPhotoSol?: number | null;
        };
        /**
         * @description Standardized API response envelope for v2 endpoints
         *     Inspired by JSON:API specification for consistency
         */
        CameraResourceListApiResponse: {
            /** @description The primary data for this response */
            data?: components["schemas"]["CameraResource"][] | null;
            meta?: components["schemas"]["ResponseMeta"];
            pagination?: components["schemas"]["PaginationInfo"];
            links?: components["schemas"]["ResponseLinks"];
        };
        /** @description Cursor-based pagination pointers */
        CursorInfo: {
            /** @description Cursor for the current page */
            current?: string | null;
            /** @description Cursor for the next page */
            next?: string | null;
            /** @description Cursor for the previous page */
            previous?: string | null;
        };
        /**
         * Format: int32
         * @description Field set types for controlling response data
         * @enum {integer}
         */
        FieldSetType: 0 | 1 | 2 | 3 | 4;
        Int32Int32ValueTuple: Record<string, never>;
        /** @description Journey attributes and statistics */
        JourneyAttributes: {
            /** @description Rover name */
            rover?: string | null;
            /**
             * Format: int32
             * @description Starting sol
             */
            solStart?: number;
            /**
             * Format: int32
             * @description Ending sol
             */
            solEnd?: number;
            /**
             * Format: float
             * @description Approximate distance traveled in kilometers
             */
            distanceTraveledKm?: number | null;
            /**
             * Format: int32
             * @description Number of unique locations visited
             */
            locationsVisited?: number;
            /**
             * Format: float
             * @description Elevation change in meters (if calculable)
             */
            elevationChangeM?: number | null;
            /**
             * Format: int32
             * @description Total photos taken during journey
             */
            totalPhotos?: number;
        };
        /** @description Links related to the journey */
        JourneyLinks: {
            /** @description Link to map visualization (future feature) */
            mapVisualization?: string | null;
            /** @description Link to KML export (future feature) */
            kmlExport?: string | null;
        };
        /** @description Journey resource representing a rover's path over a sol range */
        JourneyResource: {
            /** @description Resource type (always "journey") */
            type?: string | null;
            attributes?: components["schemas"]["JourneyAttributes"];
            /** @description Path waypoints */
            path?: components["schemas"]["JourneyWaypoint"][] | null;
            links?: components["schemas"]["JourneyLinks"];
        };
        /**
         * @description Standardized API response envelope for v2 endpoints
         *     Inspired by JSON:API specification for consistency
         */
        JourneyResourceApiResponse: {
            data?: components["schemas"]["JourneyResource"];
            meta?: components["schemas"]["ResponseMeta"];
            pagination?: components["schemas"]["PaginationInfo"];
            links?: components["schemas"]["ResponseLinks"];
        };
        /** @description A waypoint on the rover's journey */
        JourneyWaypoint: {
            /**
             * Format: int32
             * @description Sol at this waypoint
             */
            sol?: number;
            /** @description Earth date at this waypoint */
            earthDate?: string | null;
            /**
             * Format: int32
             * @description Site number
             */
            site?: number;
            /**
             * Format: int32
             * @description Drive number
             */
            drive?: number;
            coordinates?: components["schemas"]["PhotoCoordinates"];
            /**
             * Format: int32
             * @description Number of photos taken at this waypoint
             */
            photosTaken?: number;
        };
        /** @description Location attributes */
        LocationAttributes: {
            /** @description Rover name */
            rover?: string | null;
            /**
             * Format: int32
             * @description Site number
             */
            site?: number;
            /**
             * Format: int32
             * @description Drive number
             */
            drive?: number;
            /** @description Location name (if known) */
            name?: string | null;
            /** @description First date this location was visited */
            firstVisited?: string | null;
            /** @description Last date this location was visited */
            lastVisited?: string | null;
            /**
             * Format: int32
             * @description First sol this location was visited
             */
            firstSol?: number | null;
            /**
             * Format: int32
             * @description Last sol this location was visited
             */
            lastSol?: number | null;
            /**
             * Format: int32
             * @description Total number of photos taken at this location
             */
            photoCount?: number;
            /**
             * Format: int32
             * @description Number of unique visits to this location
             */
            visitCount?: number | null;
            coordinates?: components["schemas"]["PhotoCoordinates"];
        };
        /** @description Links related to the location */
        LocationLinks: {
            /** @description Link to all photos at this location */
            photos?: string | null;
            /**
             * @description Link to 360-degree view (future feature)
             *     Note: Property name starts with number, needs explicit attribute
             */
            "360View"?: string | null;
            /** @description Link to time-lapse of this location (future feature) */
            timeLapse?: string | null;
        };
        /** @description Location resource representing a unique site/drive location visited by a rover */
        LocationResource: {
            /** @description Unique location identifier (e.g., "curiosity_79_1204") */
            id?: string | null;
            /** @description Resource type (always "location") */
            type?: string | null;
            attributes?: components["schemas"]["LocationAttributes"];
            links?: components["schemas"]["LocationLinks"];
        };
        /**
         * @description Standardized API response envelope for v2 endpoints
         *     Inspired by JSON:API specification for consistency
         */
        LocationResourceListApiResponse: {
            /** @description The primary data for this response */
            data?: components["schemas"]["LocationResource"][] | null;
            meta?: components["schemas"]["ResponseMeta"];
            pagination?: components["schemas"]["PaginationInfo"];
            links?: components["schemas"]["ResponseLinks"];
        };
        /** @description Manifest attributes */
        ManifestAttributes: {
            /** @description Rover name */
            name?: string | null;
            /** @description Landing date (YYYY-MM-DD) */
            landingDate?: string | null;
            /** @description Launch date (YYYY-MM-DD) */
            launchDate?: string | null;
            /** @description Mission status */
            status?: string | null;
            /**
             * Format: int32
             * @description Maximum sol
             */
            maxSol?: number;
            /** @description Most recent photo date */
            maxDate?: string | null;
            /**
             * Format: int32
             * @description Total photos
             */
            totalPhotos?: number;
            /** @description Photo counts by sol */
            photos?: components["schemas"]["PhotosBySol"][] | null;
        };
        /** @description Pagination information supporting both page-based and cursor-based pagination */
        PaginationInfo: {
            /**
             * Format: int32
             * @description Current page number (1-indexed)
             */
            page?: number | null;
            /**
             * Format: int32
             * @description Number of items per page
             */
            perPage?: number;
            /**
             * Format: int32
             * @description Total number of pages
             */
            totalPages?: number | null;
            cursor?: components["schemas"]["CursorInfo"];
        };
        /** @description Panorama attributes */
        PanoramaAttributes: {
            /** @description Rover name */
            rover?: string | null;
            /**
             * Format: int32
             * @description Sol when panorama was taken
             */
            sol?: number;
            /** @description Mars time when panorama sequence started */
            marsTimeStart?: string | null;
            /** @description Mars time when panorama sequence ended */
            marsTimeEnd?: string | null;
            /**
             * Format: int32
             * @description Total number of photos in the panorama
             */
            totalPhotos?: number;
            /**
             * Format: float
             * @description Approximate angular coverage in degrees
             */
            coverageDegrees?: number | null;
            location?: components["schemas"]["PhotoLocation"];
            /** @description Camera used for the panorama */
            camera?: string | null;
            /**
             * Format: float
             * @description Average elevation angle
             */
            avgElevation?: number | null;
        };
        /** @description Links related to the panorama */
        PanoramaLinks: {
            /** @description Link to panorama preview/stitched image (future feature) */
            stitchedPreview?: string | null;
            /** @description Link to download all photos as a set */
            downloadSet?: string | null;
        };
        /** @description Panorama resource representing an auto-detected panoramic sequence */
        PanoramaResource: {
            /** @description Unique panorama identifier (e.g., "pano_curiosity_1000_14") */
            id?: string | null;
            /** @description Resource type (always "panorama") */
            type?: string | null;
            attributes?: components["schemas"]["PanoramaAttributes"];
            /** @description Photos that make up this panorama */
            photos?: components["schemas"]["PhotoResource"][] | null;
            links?: components["schemas"]["PanoramaLinks"];
        };
        /**
         * @description Standardized API response envelope for v2 endpoints
         *     Inspired by JSON:API specification for consistency
         */
        PanoramaResourceListApiResponse: {
            /** @description The primary data for this response */
            data?: components["schemas"]["PanoramaResource"][] | null;
            meta?: components["schemas"]["ResponseMeta"];
            pagination?: components["schemas"]["PaginationInfo"];
            links?: components["schemas"]["ResponseLinks"];
        };
        /** @description Time period information */
        PeriodInfo: {
            /** @description Start date of the period (YYYY-MM-DD) */
            from?: string | null;
            /** @description End date of the period (YYYY-MM-DD) */
            to?: string | null;
        };
        /** @description Photo attributes (data fields) */
        PhotoAttributes: {
            /** @description NASA's unique identifier for this photo */
            nasaId?: string | null;
            /**
             * Format: int32
             * @description Mars sol (day) when photo was taken
             */
            sol?: number | null;
            /** @description Earth date when photo was taken (YYYY-MM-DD) */
            earthDate?: string | null;
            /**
             * Format: date-time
             * @description UTC timestamp when photo was taken
             */
            dateTakenUtc?: string | null;
            /** @description Mars local time when photo was taken (e.g., "Sol-1000M14:23:45") */
            dateTakenMars?: string | null;
            images?: components["schemas"]["PhotoImages"];
            dimensions?: components["schemas"]["PhotoDimensions"];
            /** @description Sample type (e.g., "Full", "Thumbnail", "Subframe") */
            sampleType?: string | null;
            location?: components["schemas"]["PhotoLocation"];
            telemetry?: components["schemas"]["PhotoTelemetry"];
            /** @description Photo title */
            title?: string | null;
            /** @description Photo caption/description */
            caption?: string | null;
            /** @description Photo credit (e.g., "NASA/JPL-Caltech") */
            credit?: string | null;
            /**
             * Format: date-time
             * @description When this photo was added to our database
             */
            createdAt?: string | null;
            /** @description URL to the photo image (legacy field, use images.medium instead) */
            imgSrc?: string | null;
            /**
             * @description Raw NASA API response data (JSONB). Only included when field_set=complete.
             *     Contains all original NASA fields for data validation and debugging.
             */
            rawData?: unknown;
        };
        /** @description 3D coordinates */
        PhotoCoordinates: {
            /**
             * Format: float
             * @description X coordinate
             */
            x?: number;
            /**
             * Format: float
             * @description Y coordinate
             */
            y?: number;
            /**
             * Format: float
             * @description Z coordinate
             */
            z?: number;
        };
        /** @description Image dimensions */
        PhotoDimensions: {
            /**
             * Format: int32
             * @description Image width in pixels
             */
            width?: number;
            /**
             * Format: int32
             * @description Image height in pixels
             */
            height?: number;
        };
        /** @description Multiple image URLs for different sizes */
        PhotoImages: {
            /** @description Small size (320px wide) - for thumbnails */
            small?: string | null;
            /** @description Medium size (800px wide) - for galleries */
            medium?: string | null;
            /** @description Large size (1200px wide) - for detailed viewing */
            large?: string | null;
            /** @description Full resolution - for download and analysis */
            full?: string | null;
        };
        /** @description Location where photo was taken */
        PhotoLocation: {
            /**
             * Format: int32
             * @description Site number (geological location marker)
             */
            site?: number | null;
            /**
             * Format: int32
             * @description Drive number (rover's drive sequence)
             */
            drive?: number | null;
            coordinates?: components["schemas"]["PhotoCoordinates"];
        };
        /** @description Photo-specific computed metadata */
        PhotoMeta: {
            /** @description Whether this photo is part of a panorama sequence */
            isPanoramaPart?: boolean | null;
            /** @description Panorama sequence identifier if part of a panorama */
            panoramaSequenceId?: string | null;
            /** @description Whether this photo has a stereo pair */
            hasStereoPair?: boolean | null;
            /**
             * Format: int32
             * @description Stereo pair photo ID if available
             */
            stereoPairId?: number | null;
            /** @description Lighting conditions (e.g., "golden_hour", "midday", "evening") */
            lightingConditions?: string | null;
            /**
             * Format: int32
             * @description Number of times rover visited this location
             */
            locationVisits?: number | null;
        };
        /** @description Photo relationships (related resources) */
        PhotoRelationships: {
            rover?: components["schemas"]["ResourceReference"];
            camera?: components["schemas"]["CameraReference"];
        };
        /** @description Photo resource in v2 API format with clear separation of attributes and relationships */
        PhotoResource: {
            /**
             * Format: int32
             * @description Unique photo identifier
             */
            id?: number;
            /** @description Resource type (always "photo") */
            type?: string | null;
            attributes?: components["schemas"]["PhotoAttributes"];
            relationships?: components["schemas"]["PhotoRelationships"];
            meta?: components["schemas"]["PhotoMeta"];
        };
        /**
         * @description Standardized API response envelope for v2 endpoints
         *     Inspired by JSON:API specification for consistency
         */
        PhotoResourceApiResponse: {
            data?: components["schemas"]["PhotoResource"];
            meta?: components["schemas"]["ResponseMeta"];
            pagination?: components["schemas"]["PaginationInfo"];
            links?: components["schemas"]["ResponseLinks"];
        };
        /**
         * @description Standardized API response envelope for v2 endpoints
         *     Inspired by JSON:API specification for consistency
         */
        PhotoResourceListApiResponse: {
            /** @description The primary data for this response */
            data?: components["schemas"]["PhotoResource"][] | null;
            meta?: components["schemas"]["ResponseMeta"];
            pagination?: components["schemas"]["PaginationInfo"];
            links?: components["schemas"]["ResponseLinks"];
        };
        /** @description Response containing photo statistics and analytics */
        PhotoStatisticsResponse: {
            /**
             * Format: int32
             * @description Total count of photos in the period
             */
            totalPhotos?: number;
            period?: components["schemas"]["PeriodInfo"];
            /** @description Statistics grouped by the requested dimension (camera, rover, or sol) */
            groups?: components["schemas"]["StatisticsGroup"][] | null;
        };
        /**
         * @description Standardized API response envelope for v2 endpoints
         *     Inspired by JSON:API specification for consistency
         */
        PhotoStatisticsResponseApiResponse: {
            data?: components["schemas"]["PhotoStatisticsResponse"];
            meta?: components["schemas"]["ResponseMeta"];
            pagination?: components["schemas"]["PaginationInfo"];
            links?: components["schemas"]["ResponseLinks"];
        };
        /** @description Camera telemetry data */
        PhotoTelemetry: {
            /**
             * Format: float
             * @description Mast azimuth angle (horizontal rotation in degrees)
             */
            mastAzimuth?: number | null;
            /**
             * Format: float
             * @description Mast elevation angle (vertical tilt in degrees)
             */
            mastElevation?: number | null;
            /**
             * Format: float
             * @description Spacecraft clock at time of capture
             */
            spacecraftClock?: number | null;
        };
        /** @description Photos taken on a specific sol */
        PhotosBySol: {
            /**
             * Format: int32
             * @description Mars sol number
             */
            sol?: number;
            /** @description Earth date (YYYY-MM-DD) */
            earthDate?: string | null;
            /**
             * Format: int32
             * @description Total photos taken on this sol
             */
            totalPhotos?: number;
            /** @description Cameras that took photos on this sol */
            cameras?: string[] | null;
        };
        /** @description Reference to a related resource */
        ResourceReference: {
            /** @description Resource identifier (slug for rovers, id for others) */
            id?: string | null;
            /** @description Resource type */
            type?: string | null;
            /** @description Attributes of the related resource (when included) */
            attributes?: unknown;
        };
        /** @description Related resource links for navigation */
        ResponseLinks: {
            /** @description Link to the current resource/page */
            self?: string | null;
            /** @description Link to the next page */
            next?: string | null;
            /** @description Link to the previous page */
            previous?: string | null;
            /** @description Link to the first page */
            first?: string | null;
            /** @description Link to the last page */
            last?: string | null;
        };
        /** @description Metadata about the response */
        ResponseMeta: {
            /**
             * Format: int32
             * @description Total count of resources matching the query (before pagination)
             */
            totalCount?: number | null;
            /**
             * Format: int32
             * @description Number of resources returned in this response
             */
            returnedCount?: number;
            /** @description The query parameters that were applied */
            query?: {
                [key: string]: unknown;
            } | null;
            /**
             * Format: date-time
             * @description Response timestamp
             */
            timestamp?: string;
        };
        /** @description Rover attributes */
        RoverAttributes: {
            /** @description Rover name (capitalized) */
            name?: string | null;
            /** @description Landing date on Mars (YYYY-MM-DD) */
            landingDate?: string | null;
            /** @description Launch date from Earth (YYYY-MM-DD) */
            launchDate?: string | null;
            /** @description Mission status (active, complete) */
            status?: string | null;
            /**
             * Format: int32
             * @description Maximum sol reached by this rover
             */
            maxSol?: number;
            /** @description Most recent photo date (YYYY-MM-DD) */
            maxDate?: string | null;
            /**
             * Format: int32
             * @description Total number of photos in our database
             */
            totalPhotos?: number;
        };
        /** @description Rover manifest (photo history by sol) */
        RoverManifest: {
            /** @description Rover identifier (slug) */
            id?: string | null;
            /** @description Resource type (always "manifest") */
            type?: string | null;
            attributes?: components["schemas"]["ManifestAttributes"];
        };
        /**
         * @description Standardized API response envelope for v2 endpoints
         *     Inspired by JSON:API specification for consistency
         */
        RoverManifestApiResponse: {
            data?: components["schemas"]["RoverManifest"];
            meta?: components["schemas"]["ResponseMeta"];
            pagination?: components["schemas"]["PaginationInfo"];
            links?: components["schemas"]["ResponseLinks"];
        };
        /** @description Rover relationships */
        RoverRelationships: {
            /** @description Cameras on this rover */
            cameras?: components["schemas"]["CameraResource"][] | null;
        };
        /** @description Rover resource in v2 API format */
        RoverResource: {
            /** @description Rover identifier (slug: curiosity, perseverance, opportunity, spirit) */
            id?: string | null;
            /** @description Resource type (always "rover") */
            type?: string | null;
            attributes?: components["schemas"]["RoverAttributes"];
            relationships?: components["schemas"]["RoverRelationships"];
        };
        /**
         * @description Standardized API response envelope for v2 endpoints
         *     Inspired by JSON:API specification for consistency
         */
        RoverResourceApiResponse: {
            data?: components["schemas"]["RoverResource"];
            meta?: components["schemas"]["ResponseMeta"];
            pagination?: components["schemas"]["PaginationInfo"];
            links?: components["schemas"]["ResponseLinks"];
        };
        /**
         * @description Standardized API response envelope for v2 endpoints
         *     Inspired by JSON:API specification for consistency
         */
        RoverResourceListApiResponse: {
            /** @description The primary data for this response */
            data?: components["schemas"]["RoverResource"][] | null;
            meta?: components["schemas"]["ResponseMeta"];
            pagination?: components["schemas"]["PaginationInfo"];
            links?: components["schemas"]["ResponseLinks"];
        };
        /**
         * Format: int32
         * @description Sort direction
         * @enum {integer}
         */
        SortDirection: 0 | 1;
        /** @description Sort field with direction */
        SortField: {
            field?: string | null;
            direction?: components["schemas"]["SortDirection"];
        };
        /** @description A single group in the statistics response */
        StatisticsGroup: {
            /** @description The grouping key (camera name, rover name, or sol number as string) */
            key?: string | null;
            /**
             * Format: int32
             * @description Number of photos in this group
             */
            count?: number;
            /**
             * Format: double
             * @description Percentage of total photos (0-100)
             */
            percentage?: number | null;
            /**
             * Format: double
             * @description Average photos per sol (only for rover grouping)
             */
            avgPerSol?: number | null;
            /** @description Earth date for this sol (only for sol grouping) */
            earthDate?: string | null;
        };
        /** @description Location information for time machine query */
        TimeMachineLocation: {
            /**
             * Format: int32
             * @description Site number
             */
            site?: number;
            /**
             * Format: int32
             * @description Drive number
             */
            drive?: number;
            /**
             * Format: int32
             * @description Total visits to this location
             */
            totalVisits?: number;
            /**
             * Format: int32
             * @description Total photos from this location
             */
            totalPhotos?: number;
        };
        /** @description Time machine resource representing photos from the same location at different times */
        TimeMachineResource: {
            /**
             * Format: int32
             * @description Sol when photo was taken
             */
            sol?: number;
            /** @description Earth date when photo was taken */
            earthDate?: string | null;
            /** @description Mars time when photo was taken */
            marsTime?: string | null;
            photo?: components["schemas"]["PhotoResource"];
            /** @description Lighting conditions at this time */
            lightingConditions?: string | null;
        };
        /** @description Time machine query response */
        TimeMachineResponse: {
            location?: components["schemas"]["TimeMachineLocation"];
            /** @description Photos from different times at this location */
            data?: components["schemas"]["TimeMachineResource"][] | null;
            meta?: components["schemas"]["ResponseMeta"];
        };
        /** @description Field-level validation error details */
        ValidationError: {
            /** @description The field/parameter name that failed validation */
            field?: string | null;
            /** @description The invalid value that was provided */
            value?: unknown;
            /** @description A human-readable error message */
            message?: string | null;
            /** @description An example of a valid value */
            example?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
